### ISSUE TITLE
Set up CDN using AWS Cloudfront

### ISSUE THREAD

**Issue by zhzhang2012** [Haunter17/CS121-RecyclingApp#7]
Host the production assets through a CDN using AWS Cloudfront backed by a S3 bucket

### Tasks

- [x] Create S3 bucket for holding production assets
- [x] Create CloudFront distribution and link to S3
- [x] Configure rails to use the CDN
- [x] Test in dev & production. Make sure nothing breaks.

**Comment by zhzhang2012** [comment]
Close after testing
